name: star_shop
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.5
  get_storage: ^2.0.3
  dio: ^4.0.6
  flutter_native_splash: ^2.2.15
  flutter_svg: ^1.1.6
  flutter_launcher_icons: ^0.13.1
  permission_handler: ^10.2.0
  responsive_sizer: ^3.1.1
  intl: ^0.17.0
  otp_text_field: ^1.1.2
  curved_navigation_bar: ^1.0.3
  dropdown_button2: ^1.7.1
  fluttertoast: ^8.1.2
  group_radio_button: ^1.3.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  flutter_calendar_carousel: ^2.4.1
  animate_do: ^3.0.2
  dotted_border: ^2.0.0+3
  qr_code_scanner: ^1.0.1
  date_picker_timeline: ^1.2.3
  syncfusion_flutter_datepicker: ^21.1.39
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/ic_splashlogo.png"

flutter_native_splash:
  color: "#C19444"
  #  background_image: "assets/images/ic_splashlogo.png"

  #  image: assets/images/ic_splashlogo.png
  #  branding: assets/images/splash_image.png

  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png

  android: true
  ios: true
  #web: false

  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center

  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center

  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center

  # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  fullscreen: true

  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'

  # To enable support for Android 12, set the following parameter to true.  Defaults to false.
  android12: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/locales/
    - assets/icon/

  fonts:
    - family: Ariel
      fonts:
        - asset: assets/fonts/ariel_bold.TTF
        - asset: assets/fonts/ariel_medium.ttf
        - asset: assets/fonts/ariel_normal.TTF
        - asset: assets/fonts/ariel_light.TTF
